[workspace]
resolver = "2"
members = [
    "doppler",
    "examples",
    "feeder",
    "price-source",
    "program",
    "sdk",
    "sources/binance",
    "sources/birdeye",
    "sources/coingecko",
    "sources/coinbase",
    "sources/http-json",
    "sources/jupiter",
    "sources/tokens-xyz",
]

[workspace.package]
repository = "https://github.com/blueshift-gg/doppler"
readme = "README.md"
license-file = "LICENSE"
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
doppler = { path = "./doppler" }
doppler-price-source = { path = "./price-source" }
doppler-price-source-binance = { path = "./sources/binance" }
doppler-price-source-birdeye = { path = "./sources/birdeye" }
doppler-price-source-coingecko = { path = "./sources/coingecko" }
doppler-price-source-coinbase = { path = "./sources/coinbase" }
doppler-price-source-http-json = { path = "./sources/http-json" }
doppler-price-source-jupiter = { path = "./sources/jupiter" }
doppler-price-source-tokens-xyz = { path = "./sources/tokens-xyz" }
doppler-program = { path = "./program" }
doppler-sdk = { path = "./sdk" }
mollusk-svm = { version = "0.5.1" }
mollusk-svm-bencher = { version = "0.5.1" }
serde = { version = "1.0.219" }
serde_json = "1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
solana-account = { version = "2.2.1" }
solana-client = { version = "2.2.3" }
solana-clock = { version = "2.2.2" }
solana-compute-budget-interface = { version = "2.2.2" }
solana-hash = { version = "2.2.1" }
solana-instruction = { version = "2.3.0" }
solana-keypair = { version = "2.2.3" }
solana-program = { version = "2.3.0" }
solana-pubkey = { version = "2.3.0" }
solana-sdk-ids = { version = "2.2.1" }
solana-signer = { version = "2.2.1" }
solana-system-interface = { version = "1.0.0" }
solana-transaction = { version = "2.2.3" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
