[package]
name = "doppler-price-source-coingecko"
description = "CoinGecko price source for Doppler."
repository = { workspace = true }
readme = { workspace = true }
license-file = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
doppler-price-source = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }

[lib]
name = "doppler_price_source_coingecko"
path = "src/lib.rs"
